---
title: "Lab 4 + Lab 5 Exercises"
author: "Bryanna Matias"
date: "9/28/2020"
output: 
bibliography: references.bib
---

```{r}
library(tidyverse)
```

```{r, eval=FALSE}
download.file(url = "https://ndownloader.figshare.com/files/2292169",
              destfile = "data/surveys_complete.csv")
```

```{r}
surveys_complete <- read_csv("data/surveys_complete.csv")
```

#Plotting with ggplot2

```{r}
#To build a ggplot, we will use the following basic template:

ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point()
```

# Challenge (Optional)

```{r}
install.packages("hexbin")
```

```{r}
library("hexbin")
```

```{r}
#Assign plot to a variable
surveys_plot <- ggplot(data = surveys_complete, 
                       mapping = aes(x = weight, y = hindfoot_length))
```

```{r}
#Draw Plot
surveys_plot + 
  geom_point()
```

```{r}
surveys_plot + 
  geom_hex()
```

#Building your plots iteratively

```{r}
#Define the Dataset
ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
    geom_point()
```

```{r}
#Modify the Dataset
ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1)
```
 
```{r}
#Adding Colors

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1, color = "blue")
```

```{r}
#Adding color to each species with species_id:

ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1, aes(color = species_id))
```

#Challenge 1

```{r}
#Use what you just learned to create a scatter plot of weight over species_id with the plot types showing in different colors. Is this a good way to show this type of data?

ggplot(data = surveys_complete, 
       mapping = aes(x = species_id, y = weight)) +
   geom_point(aes(color = plot_type))
```

#Boxplot

```{r}
#We can use boxplots to visualize the distribution of weight within each species:

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_boxplot()
```

```{r}
# By adding points to the boxplot, we can have a better idea of the number of measurements and of their distribution:

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_boxplot(alpha = 0) +
    geom_jitter(alpha = 0.3, color = "tomato")
```

# Challenge 2

```{r}
# Replace the box plot with a violin plot
ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_violin() 
```

```{r}
# Incrementally adding commands: scale_y_log10
ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_violin() +
  scale_y_log10()
```

```{r}
#So far, we’ve looked at the distribution of weight within species. Try making a new plot to explore the distribution of another variable within each species.

ggplot(data = surveys_complete, mapping = aes(x = species_id, y = hindfoot_length)) +
    geom_boxplot() +
    geom_jitter(aes(color = "plot_id"))
```

# Lab 5 Challenges: Plotting Time Series Date

```{r}
#Let’s calculate number of counts per year for each genus. First we need to group the data and count records within each group:

yearly_counts <- surveys_complete %>%
  count(year, genus)
```

```{r}
#Timelapse data can be visualized as a line plot with years on the x-axis and counts on the y-axis:
ggplot(data = yearly_counts, aes(x = year, y = n, group = genus)) +
     geom_line()
# The data is plotted all together and needs to be modified
```

```{r}
#Modifying the aesthetic function to include: group = genus
ggplot(data = yearly_counts, aes(x = year, y = n, group = genus)) +
     geom_line()
```

```{r}
#We will be able to distinguish species in the plot if we add colors (using color also automatically groups the data):

ggplot(data = yearly_counts, aes(x = year, y = n, color = genus)) +
    geom_line()
```


#Integrating the pipe operator with ggplot2

```{r}
#In the previous lesson, we saw how to use the pipe operator %>% to use different functions in a sequence and create a coherent workflow. We can also use the pipe operator to pass the data argument to the ggplot() function. 

yearly_counts %>% 
    ggplot(mapping = aes(x = year, y = n, color = genus)) +
    geom_line()
```

```{r}
# The pipe operator can also be used to link data manipulation with consequent data visualization.

yearly_counts_graph <- surveys_complete %>%
    count(year, genus) %>% 
    ggplot(mapping = aes(x = year, y = n, color = genus)) +
    geom_line()

yearly_counts_graph
```

#Faceting

```{r}
#ggplot has a special technique called faceting that allows the user to split one plot into multiple plots based on a factor included in the dataset. We will use it to make a time series plot for each species:

ggplot(data = yearly_counts, aes(x = year, y = n)) +
  geom_line() +
  facet_wrap(facets = vars(genus))
```

```{r}
# Now we would like to split the line in each plot by the sex of each individual measured. To do that we need to make counts in the data frame grouped by year, genus, and sex:

 yearly_sex_counts <- surveys_complete %>%
                      count(year, genus, sex)
```

```{r}
# We can now make the faceted plot by splitting further by sex using color (within a single plot):

ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_wrap(facets =  vars(genus))
```

```{r}
#You can also organise the panels only by rows (or only by columns):

# One column, facet by rows
ggplot(data = yearly_sex_counts, 
       mapping = aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_grid(rows = vars(genus))

# One row, facet by column
ggplot(data = yearly_sex_counts, 
       mapping = aes(x = year, y = n, color = sex)) +
  geom_line() +
  facet_grid(cols = vars(genus))
```

# ggplot2 themes

```{r}
# There are pre-loaded themes available that change the overall appearance of the graph without much effort.For example, we can change our previous graph to have a simpler white background using the theme_bw() function, and a darker background using the theme_dark function:

ggplot(data = yearly_sex_counts, 
        mapping = aes(x = year, y = n, color = sex)) +
     geom_line() +
     facet_wrap(vars(genus)) +
     theme_bw()

ggplot(data = yearly_sex_counts, 
        mapping = aes(x = year, y = n, color = sex)) +
     geom_line() +
     facet_wrap(vars(genus)) +
     theme_dark()

# There are other functions that can change the background as a starting point to create a new hand-crafted theme: theme_minimal() and theme_light() are popular, and theme_void()
```

# Challenge 1

```{r}
# Use what you just learned to create a plot that depicts how the average weight of each species changes through the years.

yearly_weight <- surveys_complete %>%
                group_by(year, species_id) %>%
                 summarize(avg_weight = mean(weight))
```

```{r}
ggplot(data = yearly_weight, mapping = aes(x=year, y=avg_weight)) +
   geom_line() +
   facet_wrap(vars(species_id)) +
   theme_void()
```

# Customization

```{r}
#Now, let’s change names of axes to something more informative than ‘year’ and ‘n’ and add a title to the figure:

ggplot(data = yearly_sex_counts, aes(x = year, y = n, color = sex)) +
    geom_line() +
    facet_wrap(vars(genus)) +
    labs(title = "Observed genera through time",
         x = "Year of observation",
         y = "Number of individuals") +
    theme_dark()
```

```{r}
# The axes have more informative names, but their readability can be improved by increasing the font size. This can be done with the generic theme() function:

ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
    geom_line() +
    facet_wrap(vars(genus)) +
    labs(title = "Observed genera through time",
        x = "Year of observation",
        y = "Number of individuals") +
    theme_dark() +
    theme(text=element_text(size = 16))
```

```{r}
#Let’s change the orientation of the labels and adjust them vertically and horizontally so they don’t overlap. You can use a 90 degree angle, or experiment to find the appropriate angle for diagonally oriented labels. We can also modify the facet label text (strip.text) to italicize the genus names:

ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
    geom_line() +
    facet_wrap(vars(genus)) +
    labs(title = "Observed genera through time",
        x = "Year of observation",
        y = "Number of individuals") +
    theme_dark() +
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 90, hjust = 0.5, vjust = 0.5),
                        axis.text.y = element_text(colour = "grey20", size = 12),
                        strip.text = element_text(face = "italic"),
                        text = element_text(size = 16))
```

```{r}
#If you like the changes you created better than the default theme, you can save them as an object to be able to easily apply them to other plots you may create:

grey_theme <- theme(axis.text.x = element_text(colour="grey20", size = 12, 
                                               angle = 90, hjust = 0.5, 
                                               vjust = 0.5),
                    axis.text.y = element_text(colour = "grey20", size = 12),
                    text=element_text(size = 16))

ggplot(surveys_complete, aes(x = species_id, y = hindfoot_length)) +
    geom_boxplot() +
    grey_theme
```

# Challenge 2

```{r}
# With all of this information in hand, please take another five minutes to either improve one of the plots generated in this exercise or create a beautiful graph of your own.

ggplot(data = yearly_sex_counts, mapping = aes(x = year, y = n, color = sex)) +
    geom_line() +
    facet_wrap(vars(genus)) +
    labs(title = "Observed genera through time",
        x = "Year of observation",
        y = "Number of individuals") +
    theme_dark() +
    theme(axis.text.x = element_text(colour = "grey20", size = 12, angle = 90, hjust = 0.5, vjust = 0.5),
                        axis.text.y = element_text(colour = "grey20", size = 7),
                        strip.text = element_text(face = "italic"),
                        text = element_text(size = 11))

```
Application written in R [@RCoreTeam] using the Shiny framework [@Chang2015].

# References











