---
title: "EvoGeno Lab 5"
author: "Bryanna Matias"
date: "9/21/2020"
output: html_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
Confirmed_State_6_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-13-2020.csv")) %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
```

```{r}
str(Confirmed_State_6_13)
```

```{r}
Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
```

```{r}
str(Confirmed_State_9_13)
```

```{r}
setdiff(Confirmed_State_9_13$Province_State, Confirmed_State_6_13$Province_State)
```

```{r}
Confirmed_State_9_13 <- Confirmed_State_9_13 %>% 
  filter(Province_State != "Recovered") 
```

# Exercise 1

* Lab 5: [Data Visualization tutorial](EvoGeno_Lab4A.html) 

```{r}
# see Lab 5 Challenges: Plotting Time Series Data
```

# Exercise 2

```{r}
# Revise the above example for joining tables using 6/13/2020 and 9/13/2020. Plot the data as a bar plot. Make sure your graph looks nice in the report by adjusting the height of the graph in the R code chunk header.

Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State"))
head(Confirmed_State_6_13_9_13_joined)
```

```{r}
# Let’s turn the NAs into 0. Also notice that we know have columns Confirmed.x Country_Region.x, Confirmed.y Country_Region.y. So let’s rename the Confirmed columns and delete the Country_Region columns

Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State")) %>% 
      rename(Confirmed_6_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
      select(-Country_Region.x, -Country_Region.y) %>% 
      replace_na(list(Confirmed_6_13_2020 = 0))
head(Confirmed_State_6_13_9_13_joined)
```

```{r, fig.width = 5, fig.height = 10}
# Switching between wide and long table formats.

Confirmed_State_6_13_9_13_joined_long <- Confirmed_State_6_13_9_13_joined %>% 
              pivot_longer(-c(Province_State),
                            names_to = "Date", values_to = "Confirmed")

ggplot(Confirmed_State_6_13_9_13_joined_long, aes(x = Confirmed,  y = Province_State))  + geom_bar(stat="identity",aes(color = Date))
```

```{r, fig.width = 5, fig.height = 10}

ggplot(Confirmed_State_6_13_9_13_joined_long, aes(x = Confirmed,  y = Province_State))  + 
    geom_point(aes(color = Date)) 
```

# Exercise 3

```{r, fig.width = 5, fig.height = 10}
# Add more informative x and y labels and a title to the above graph in Ex2.

ggplot(Confirmed_State_6_13_9_13_joined_long, aes(x = Confirmed,  y = Province_State))  + geom_bar(stat="identity",aes(color = Date)) +  labs(title="COVID-19 Confirmed Cases in US",
        x ="Number of Confirmed Cases", y = "State/Province in US")
```

# Working with the time series data

```{r}
library(lubridate)
```

```{r}
# Load the most recent time series data for confrimed cases

time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")

 download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv", 
               destfile = "data/time_series_covid19_confirmed_global.csv")
 
 time_series_confirmed <- read_csv("data/time_series_covid19_confirmed_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
 
# Check the table properties to make sure the data imported as we expected

head(time_series_confirmed)
```

```{r}
# Convert the data from wide format to long format

time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") 

head(time_series_confirmed_long)
```
```{r}
# It would be convenient to have the confirmed cases and deaths in the same table. We can create another table with the deaths and then join the two tables. Download: 

 download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
               destfile = "data/time_series_covid19_deaths_global.csv")
```

```{r}
time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```

```{r}
# Convert wide format to long format

time_series_deaths_long <- time_series_deaths %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Deaths") 
head(time_series_deaths_long)
```

# Joining the Time Series Tables

```{r}
# To join 2 tables we need a common column in which each row is a unique name. This is often called the Key. 

time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)

time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)
```

```{r}
time_series_long_joined <- full_join(time_series_confirmed_long,
              time_series_deaths_long, by = c("Key")) %>% 
              select(-Key)
head(time_series_long_joined)
     
#which(is.na(time_series_long_joined$Confirmed))

#which(is.na(time_series_long_joined$Deaths))

time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
```

# Exercise 4

```{r}
# Using the time series data. Make a plot of the total number of confirmed deaths per day worldwide

time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("Worldwide COVID-19 Deaths")
```

# Exercise 5

```{r}
# Use Mutate to make a new column with deaths/confirmed cases (Hint: this might be best done after joining the tables, but before pivoting longer)

time_series_long_joined %>% 
  mutate(rate = Deaths/Confirmed, percent = rate * 100)
```

```{r}
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date, Deaths/Confirmed),
               names_to = "Report_Type", values_to = "Counts")
str(time_series_long_joined_counts)
```

# Exercise 6

```{r}
# Plot US deaths/confirmed cases per day.

time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Deaths")
```

# Exercise 7

```{r}
# Make a single graph with from the times series data with the 10 countries with the highest death total.

time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% c("US","Brazil","India","Italy", 
                                "Mexico","Spain","France","Iran","Peru","UK")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("Top 10 Countries W/ COVID-19 Deaths")
```

# Exercise 8

```{r, fig.width = 6, fig.height = 10}
# Using Facet_Wraps make a graph from the times series data with the 10 countries with the highest death total. Format the table to look nice in the report by changing the number of rows in your graph and/or adjusting the height in the R code chunk header.

time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("US","Brazil","India","Italy", 
                                "Mexico","Spain","France","Iran","Peru","UK")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")
```

# Exercise 9

```{r}
# Using Facet_Wraps make a graph from the times series data for confirmed cases for all US states and territories. (Hint: Instead of the global time series use the US time series data in the same folder time_series_covid19_deaths_US.csv and time_series_covid19_confirmed_US.csv) Format the table to look nice in the report by changing the number of rows in your graph and/or adjusting the height in the R code chunk header. Notice that there are many more fields in the US report than the global report and that the US Deaths table has an extra column for Population. 

 download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv", 
               destfile = "data/time_series_covid19_confirmed_US.csv")

 download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv", 
               destfile = "data/time_series_covid19_deaths_US.csv")
```

```{r}
time_series_confirmed_US <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv"))

head(time_series_confirmed_US)
```

```{r}
time_series_deaths_US <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv"))

head(time_series_deaths_US)
```
```{r}
time_series_confirmed_US_long <- time_series_confirmed_US %>% 
               pivot_longer(-c(UID, iso2, iso3, code3, FIPS, Admin2, Combined_Key, Province_State, Country_Region, Lat),
                            names_to = "Date", values_to = "Confirmed") 

head(time_series_confirmed_long)
```

```{r}
time_series_deaths_US_long <- time_series_deaths_US %>% 
               pivot_longer(-c(UID, iso2, iso3, code3, FIPS, Admin2, Combined_Key, Province_State, Country_Region, Lat),
                            names_to = "Date", values_to = "Deaths") 
head(time_series_deaths_long)
```

# Exercise 10

```{r, fig.width = 6, fig.height = 10}
# Apply a theme other than the one used in the Data Carpentries tutorial to the graph in Ex8.

time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("US","Brazil","India","Italy", 
                                "Mexico","Spain","France","Iran","Peru","UK")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("Global COVID-19 Deaths") + 
    facet_wrap(~Country_Region, ncol=2, scales="free_y") + theme_dark() + theme(axis.text.x = element_text(colour = "Purple", size = 12, angle = 90, hjust = 0.5, vjust = 0.5),
                        axis.text.y = element_text(colour = "Purple", size = 12),
                        strip.text = element_text(face = "italic", "bold", colour = "Purple"),
                        text = element_text(size = 16)) + theme( panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "Purple"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "Purple")) 
```

Application written in R [@RCoreTeam] using the Shiny framework [@Chang2015].

# References



