---
title: "Lab 9x"
author: "Bryanna Matias"
date: "12/1/2020"
output: html_document
bibliography: references.bib
---

# Conditional statements with if-else
```{r, if_ex1}
Homework <- 100 
if(Homework == 100) {
        print ("Passing Grade")
} else {
        print("Failing Grade")
}
```
```{r, if_ex2}
Homework <- 100 
if(Homework == 100) {
        print ("Passing Grade")
} else if(Homework < 75) {
        print("Average Grade")
} else if(Homework < 60) {
        print("Failing Grade")
}
```

```{r}
x <- runif(1, 0, 10)  
if(x > 3) {
        y <- 10
} else {
        y <- 0
}
```

# For loops
```{r, for_ex1}
for (i in 1:21){
  if (i > 18){
    print(i)
  }
}
```

```{r, for_ex2}
x <- c("a", "e", "i", "o", "u")
for(i in 1:5) {
        ## Print out each element of 'x'
        print(x[i])  
}
```

```{r, for_ex3}
## Generate a sequence based on length of 'x'
for(i in seq_along(x)) {   
        print(x[i])
}
```

```{r, for_ex4}
for(letter in x) {
        print(letter)
}
```

# Nested for loops
```{r, nested_ex1}
x <- matrix(1:5, 5, 10)
for(i in seq_len(nrow(x))) {
        for(j in seq_len(ncol(x))) {
                print(x[i, j])
        }   
}
```

# While loops
```{r, whileloop_ex1}
Yay <- 5
while (2*Yay <= 20){
  print("Happy Yay")
  Yay=Yay+2
}
```

```{r, whileloop_ex2}
z <- 10
set.seed(1)
while(z >= 6 && z <= 10) {
        coin <- rbinom(1, 1, 0.5)
        
        if(coin == 1) {  ## random walk
                z <- z + 3
        } else {
                z <- z - 2
        } 
}
print(z)
```

# Functions 
```{r, function_ex1}
# Here’s a simple function that takes no arguments and does nothing.
f <- function() {
         ## This is an empty function
 }
 ## Functions have their own class
 class(f)  
## Execute this function
f()       
```

```{r, function_ex2}
# The next thing we can do is create a function that actually has a non-trivial function body.
f <- function() {
        cat("Have a Good Break!\n")
 }
 f()
```
```{r, function_ex3}
# The last aspect of a basic function is the function arguments. These are the options that you can specify to the user that the user may explicity set. For this basic function, we can add an argument that determines how many times “Hello, world!” is printed to the console.
f <- function(num) {
  for(i in seq_len(num)) {
        cat("You Too!\n")
  }
 }
 f(5)
```

```{r, function_ex4}
# This next function returns the total number of characters printed to the console.
f <- function(num) {
         hello <- "Happy Holidays!\n"
         for(i in seq_len(num)) {
                 cat(hello)
         }
         chars <- nchar(hello) * num
         chars
 }
 meaningoflife <- f(3)
 print(meaningoflife)
```
```{r, fucntion_ex5}
# setting a default value for the argument num
f <- function(num = 1) {
         hello <- "Merry Christmas!\n"
         for(i in seq_len(num)) {
                 cat(hello)
         }
         chars <- nchar(hello) * num
         chars
 }
 f()    ## Use default value for 'num'
f(2)
```
```{r, function_ex6}
f(num = 10)
```

Application written in R [@RCoreTeam] using the Shiny framework [@Chang2015].
# REFERENCES